services:
  db:
    image: postgres:16
    container_name: congel_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: congel
    ports:
      - "5432:5432"
    volumes:
      - congel_pgdata:/var/lib/postgresql/data

volumes:
  congel_pgdata:
